<a href="https://colab.research.google.com/github/omartru10/machile-learning/blob/main/RNA/covid-19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/omartru10/machile-learning/main/datasets/covid_19_data.csv")
df.head()

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [ ]:
# Vamos a crear un funcion para limpiar las cabeceras del dataset

def format_column_names(df):
    df.columns = df.columns.str.lower().str.replace(" ","_", regex=True)
    df.columns = df.columns.str.replace(".","_", regex=True)
    df.columns = df.columns.str.replace("-","_", regex=True)
    df.columns = df.columns.str.replace(":","_", regex=True)

In [ ]:
format_column_names(df)
df.head()

sno observationdate province/state  country/region      last_update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   confirmed  deaths  recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [ ]:
df.drop(columns=['sno','province/state','last_update'], axis=1, inplace=True)

In [ ]:
df.head()

observationdate  country/region  confirmed  deaths  recovered
0      01/22/2020  Mainland China        1.0     0.0        0.0
1      01/22/2020  Mainland China       14.0     0.0        0.0
2      01/22/2020  Mainland China        6.0     0.0        0.0
3      01/22/2020  Mainland China        1.0     0.0        0.0
4      01/22/2020  Mainland China        0.0     0.0        0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   observationdate  306429 non-null  object 
 1   country/region   306429 non-null  object 
 2   confirmed        306429 non-null  float64
 3   deaths           306429 non-null  float64
 4   recovered        306429 non-null  float64
dtypes: float64(3), object(2)
memory usage: 11.7+ MB


In [ ]:
df['observationdate'] = pd.to_datetime(df['observationdate'])

In [ ]:
df.head()

observationdate  country/region  confirmed  deaths  recovered
0      2020-01-22  Mainland China        1.0     0.0        0.0
1      2020-01-22  Mainland China       14.0     0.0        0.0
2      2020-01-22  Mainland China        6.0     0.0        0.0
3      2020-01-22  Mainland China        1.0     0.0        0.0
4      2020-01-22  Mainland China        0.0     0.0        0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   observationdate  306429 non-null  datetime64[ns]
 1   country/region   306429 non-null  object        
 2   confirmed        306429 non-null  float64       
 3   deaths           306429 non-null  float64       
 4   recovered        306429 non-null  float64       
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 11.7+ MB


In [ ]:
df['year'] = df['observationdate'].dt.year
df['month'] = df['observationdate'].dt.month
df['day'] = df['observationdate'].dt.day
df.drop(columns=['observationdate'], axis=1, inplace=True)

In [ ]:
df.head()

country/region  confirmed  deaths  recovered  year  month  day
0  Mainland China        1.0     0.0        0.0  2020      1   22
1  Mainland China       14.0     0.0        0.0  2020      1   22
2  Mainland China        6.0     0.0        0.0  2020      1   22
3  Mainland China        1.0     0.0        0.0  2020      1   22
4  Mainland China        0.0     0.0        0.0  2020      1   22

In [26]:
df = df[['country/region','day','month','year','confirmed','deaths','recovered']]

In [27]:
df.head()

country/region  day  month  year  confirmed  deaths  recovered
0  Mainland China   22      1  2020        1.0     0.0        0.0
1  Mainland China   22      1  2020       14.0     0.0        0.0
2  Mainland China   22      1  2020        6.0     0.0        0.0
3  Mainland China   22      1  2020        1.0     0.0        0.0
4  Mainland China   22      1  2020        0.0     0.0        0.0

In [29]:
x = df.iloc[:,1:6].values
x

array([[2.20000e+01, 1.00000e+00, 2.02000e+03, 1.00000e+00, 0.00000e+00],
       [2.20000e+01, 1.00000e+00, 2.02000e+03, 1.40000e+01, 0.00000e+00],
       [2.20000e+01, 1.00000e+00, 2.02000e+03, 6.00000e+00, 0.00000e+00],
       ...,
       [2.90000e+01, 5.00000e+00, 2.02100e+03, 1.36400e+03, 1.00000e+00],
       [2.90000e+01, 5.00000e+00, 2.02100e+03, 8.75500e+04, 1.73800e+03],
       [2.90000e+01, 5.00000e+00, 2.02100e+03, 3.91559e+05, 4.25200e+03]])

In [30]:
y = df.iloc[:,6].values
y

array([    0.,     0.,     0., ...,  1324., 83790.,     0.])

In [31]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder_x1 = LabelEncoder()
x[:,0] = LabelEncoder_x1.fit_transform(x[:,0])


In [32]:
x


array([[2.10000e+01, 1.00000e+00, 2.02000e+03, 1.00000e+00, 0.00000e+00],
       [2.10000e+01, 1.00000e+00, 2.02000e+03, 1.40000e+01, 0.00000e+00],
       [2.10000e+01, 1.00000e+00, 2.02000e+03, 6.00000e+00, 0.00000e+00],
       ...,
       [2.80000e+01, 5.00000e+00, 2.02100e+03, 1.36400e+03, 1.00000e+00],
       [2.80000e+01, 5.00000e+00, 2.02100e+03, 8.75500e+04, 1.73800e+03],
       [2.80000e+01, 5.00000e+00, 2.02100e+03, 3.91559e+05, 4.25200e+03]])

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0 )
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test =  st.transform(x_test)

In [34]:
x.shape[0]

306429

In [35]:
x

array([[2.10000e+01, 1.00000e+00, 2.02000e+03, 1.00000e+00, 0.00000e+00],
       [2.10000e+01, 1.00000e+00, 2.02000e+03, 1.40000e+01, 0.00000e+00],
       [2.10000e+01, 1.00000e+00, 2.02000e+03, 6.00000e+00, 0.00000e+00],
       ...,
       [2.80000e+01, 5.00000e+00, 2.02100e+03, 1.36400e+03, 1.00000e+00],
       [2.80000e+01, 5.00000e+00, 2.02100e+03, 8.75500e+04, 1.73800e+03],
       [2.80000e+01, 5.00000e+00, 2.02100e+03, 3.91559e+05, 4.25200e+03]])

In [38]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from tensorflow import keras
model = Sequential()
model.add(Dense(units=3, kernel_initializer="uniform", activation="relu", input_dim=5))
model.add(Dropout(0.1))
model.add(Dense(units=3, kernel_initializer="uniform", activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(units=1, kernel_initializer="uniform", activation="relu"))

##model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])

In [ ]:
model.fit(x_train, y_train,batch_size=10,epochs=100) 


Epoch 1/100
 6733/24515 [=======>......................] - ETA: 27s - loss: 45789773824.0000 - mean_squared_error: 45789773824.0000