<a href="https://colab.research.google.com/github/omartru10/machile-learning/blob/main/RNA/covid-19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
df = pd.read_csv("https://raw.githubusercontent.com/omartru10/machile-learning/main/datasets/covid_19_data.csv")
df.head()

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [40]:
# Vamos a crear un funcion para limpiar las cabeceras del dataset

def format_column_names(df):
    df.columns = df.columns.str.lower().str.replace(" ","_", regex=True)
    df.columns = df.columns.str.replace(".","_", regex=True)
    df.columns = df.columns.str.replace("-","_", regex=True)
    df.columns = df.columns.str.replace(":","_", regex=True)

In [41]:
format_column_names(df)
df.head()

sno observationdate province/state  country/region      last_update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   confirmed  deaths  recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [42]:
df.drop(columns=['sno','province/state','last_update'], axis=1, inplace=True)

In [43]:
df.head()

observationdate  country/region  confirmed  deaths  recovered
0      01/22/2020  Mainland China        1.0     0.0        0.0
1      01/22/2020  Mainland China       14.0     0.0        0.0
2      01/22/2020  Mainland China        6.0     0.0        0.0
3      01/22/2020  Mainland China        1.0     0.0        0.0
4      01/22/2020  Mainland China        0.0     0.0        0.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   observationdate  306429 non-null  object 
 1   country/region   306429 non-null  object 
 2   confirmed        306429 non-null  float64
 3   deaths           306429 non-null  float64
 4   recovered        306429 non-null  float64
dtypes: float64(3), object(2)
memory usage: 11.7+ MB


In [45]:
df['observationdate'] = pd.to_datetime(df['observationdate'])

In [46]:
df.head()

observationdate  country/region  confirmed  deaths  recovered
0      2020-01-22  Mainland China        1.0     0.0        0.0
1      2020-01-22  Mainland China       14.0     0.0        0.0
2      2020-01-22  Mainland China        6.0     0.0        0.0
3      2020-01-22  Mainland China        1.0     0.0        0.0
4      2020-01-22  Mainland China        0.0     0.0        0.0

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   observationdate  306429 non-null  datetime64[ns]
 1   country/region   306429 non-null  object        
 2   confirmed        306429 non-null  float64       
 3   deaths           306429 non-null  float64       
 4   recovered        306429 non-null  float64       
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 11.7+ MB


In [48]:
df['year'] = df['observationdate'].dt.year
df['month'] = df['observationdate'].dt.month
df['day'] = df['observationdate'].dt.day
df.drop(columns=['observationdate'], axis=1, inplace=True)

In [49]:
df.head()

country/region  confirmed  deaths  recovered  year  month  day
0  Mainland China        1.0     0.0        0.0  2020      1   22
1  Mainland China       14.0     0.0        0.0  2020      1   22
2  Mainland China        6.0     0.0        0.0  2020      1   22
3  Mainland China        1.0     0.0        0.0  2020      1   22
4  Mainland China        0.0     0.0        0.0  2020      1   22

In [51]:
df = df[['country/region','year','month','day','confirmed','deaths','recovered']]

In [52]:
df.head()

country/region  year  month  day  confirmed  deaths  recovered
0  Mainland China  2020      1   22        1.0     0.0        0.0
1  Mainland China  2020      1   22       14.0     0.0        0.0
2  Mainland China  2020      1   22        6.0     0.0        0.0
3  Mainland China  2020      1   22        1.0     0.0        0.0
4  Mainland China  2020      1   22        0.0     0.0        0.0

In [53]:
x = df.iloc[:,1:6].values
x

array([[2.02000e+03, 1.00000e+00, 2.20000e+01, 1.00000e+00, 0.00000e+00],
       [2.02000e+03, 1.00000e+00, 2.20000e+01, 1.40000e+01, 0.00000e+00],
       [2.02000e+03, 1.00000e+00, 2.20000e+01, 6.00000e+00, 0.00000e+00],
       ...,
       [2.02100e+03, 5.00000e+00, 2.90000e+01, 1.36400e+03, 1.00000e+00],
       [2.02100e+03, 5.00000e+00, 2.90000e+01, 8.75500e+04, 1.73800e+03],
       [2.02100e+03, 5.00000e+00, 2.90000e+01, 3.91559e+05, 4.25200e+03]])

In [54]:
y = df.iloc[:,6].values
y

array([    0.,     0.,     0., ...,  1324., 83790.,     0.])

In [55]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder_x1 = LabelEncoder()
x[:,0] = LabelEncoder_x1.fit_transform(x[:,0])


In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0 )
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test =  st.transform(x_test)

In [57]:
x.shape[0]

306429

In [58]:
x

array([[0.00000e+00, 1.00000e+00, 2.20000e+01, 1.00000e+00, 0.00000e+00],
       [0.00000e+00, 1.00000e+00, 2.20000e+01, 1.40000e+01, 0.00000e+00],
       [0.00000e+00, 1.00000e+00, 2.20000e+01, 6.00000e+00, 0.00000e+00],
       ...,
       [1.00000e+00, 5.00000e+00, 2.90000e+01, 1.36400e+03, 1.00000e+00],
       [1.00000e+00, 5.00000e+00, 2.90000e+01, 8.75500e+04, 1.73800e+03],
       [1.00000e+00, 5.00000e+00, 2.90000e+01, 3.91559e+05, 4.25200e+03]])

In [59]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from tensorflow import keras
model = Sequential()
model.add(Dense(units=3, kernel_initializer="uniform", activation="relu", input_dim=5))
model.add(Dropout(0.1))
model.add(Dense(units=3, kernel_initializer="uniform", activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(units=1, kernel_initializer="uniform", activation="relu"))

model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adam(),metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train,batch_size=10,epochs=100)

Epoch 1/100
13421/24515 [===============>..............] - ETA: 18s - loss: nan - accuracy: 0.2222